/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author USER
 */
public class Calculation extends javax.swing.JFrame {

    
    float f1;
    float f2;
    float f3;
    float f4;
    float f5;
    float f6;
    float f7;
    float f8;
    float f9;
    float f10;
    float f11;
    float f12;
    float f13;
    float f14;
    float f15;
    float f16;
    float f17;
    float f18;
    float f19;
    float f20;
    float f21;
    float total_drinks;
    float total_nonveges;
    float  total_veges;
    float sub_total;
    float tax;
    float total;
    
    public Calculation() {
        initComponents();
        showdate();
        showtime();
       
        
    }
    void showdate()
    {
     Date d=new Date();
     SimpleDateFormat d1=new SimpleDateFormat("dd-MM-yyyy");
     jLabel15.setText(d1.format(d));
    }
    void showtime()
    {
       new Timer(0,new ActionListener(){
         
           @Override
           public void actionPerformed(ActionEvent e)
           {
                 Date d=new Date();
                 SimpleDateFormat d1=new SimpleDateFormat("hh:mm:ss a");
                 jLabel11.setText(d1.format(d));
           
            }
       } ).start();
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jCheckBox22 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(4, 0));
        setPreferredSize(new java.awt.Dimension(1358, 728));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ITEMS");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 0, 0), null, null));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 10, 170, 44);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 870, 60);

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 4));
        jPanel2.setLayout(null);

        jLabel11.setBackground(new java.awt.Color(255, 0, 0));
        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jPanel2.add(jLabel11);
        jLabel11.setBounds(310, 10, 150, 30);

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 51));
        jLabel12.setText("Time :");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(250, 10, 60, 30);

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Date :");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 10, 60, 30);

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel14.setText("Date :");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 10, 60, 30);

        jLabel15.setBackground(new java.awt.Color(255, 0, 0));
        jLabel15.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jPanel2.add(jLabel15);
        jLabel15.setBounds(90, 10, 150, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(875, 0, 475, 60);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 4));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NON-VEGES");
        jLabel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jPanel4.add(jLabel4);
        jLabel4.setBounds(70, 0, 120, 30);

        jCheckBox15.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox15.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox15.setText("Mutton Korma");
        jCheckBox15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox15.setOpaque(false);
        jCheckBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox15ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox15);
        jCheckBox15.setBounds(10, 60, 190, 30);

        jCheckBox16.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox16.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox16.setText("Chiken Reajala");
        jCheckBox16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox16.setOpaque(false);
        jCheckBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox16ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox16);
        jCheckBox16.setBounds(10, 120, 200, 30);

        jCheckBox17.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox17.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox17.setText("Katla Fish Kari");
        jCheckBox17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox17.setOpaque(false);
        jCheckBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox17ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox17);
        jCheckBox17.setBounds(10, 180, 200, 30);

        jCheckBox18.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox18.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox18.setText("Katol Kalia");
        jCheckBox18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox18.setOpaque(false);
        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox18);
        jCheckBox18.setBounds(10, 240, 160, 30);

        jCheckBox19.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox19.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox19.setText("Nihari Gosht");
        jCheckBox19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox19.setOpaque(false);
        jCheckBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox19ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox19);
        jCheckBox19.setBounds(10, 360, 180, 30);

        jCheckBox20.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox20.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox20.setText("Butter chiken");
        jCheckBox20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox20.setOpaque(false);
        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox20);
        jCheckBox20.setBounds(10, 420, 180, 30);

        jCheckBox21.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox21.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox21.setText("Chiken 65");
        jCheckBox21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox21.setOpaque(false);
        jCheckBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox21ActionPerformed(evt);
            }
        });
        jPanel4.add(jCheckBox21);
        jCheckBox21.setBounds(10, 300, 160, 30);

        jTextField15.setEditable(false);
        jTextField15.setBackground(new java.awt.Color(255, 255, 102));
        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("0");
        jTextField15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField15);
        jTextField15.setBounds(210, 60, 50, 30);

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(255, 255, 102));
        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("0");
        jTextField16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField16);
        jTextField16.setBounds(210, 120, 50, 30);

        jTextField17.setEditable(false);
        jTextField17.setBackground(new java.awt.Color(255, 255, 102));
        jTextField17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("0");
        jTextField17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField17);
        jTextField17.setBounds(210, 180, 50, 30);

        jTextField18.setEditable(false);
        jTextField18.setBackground(new java.awt.Color(255, 255, 102));
        jTextField18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("0");
        jTextField18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField18);
        jTextField18.setBounds(210, 300, 50, 30);

        jTextField19.setEditable(false);
        jTextField19.setBackground(new java.awt.Color(255, 255, 102));
        jTextField19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("0");
        jTextField19.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField19);
        jTextField19.setBounds(210, 360, 50, 30);

        jTextField20.setEditable(false);
        jTextField20.setBackground(new java.awt.Color(255, 255, 102));
        jTextField20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("0");
        jTextField20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField20);
        jTextField20.setBounds(210, 420, 50, 30);

        jTextField21.setEditable(false);
        jTextField21.setBackground(new java.awt.Color(255, 255, 102));
        jTextField21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("0");
        jTextField21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.add(jTextField21);
        jTextField21.setBounds(210, 240, 50, 30);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(590, 10, 270, 480);

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DRINKS");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jPanel5.add(jLabel2);
        jLabel2.setBounds(60, 0, 120, 30);

        jCheckBox1.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox1.setText("Shikanji");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox1);
        jCheckBox1.setBounds(10, 240, 160, 30);

        jCheckBox2.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox2.setText("Sugarcane juice");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox2.setOpaque(false);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox2);
        jCheckBox2.setBounds(10, 60, 200, 40);

        jCheckBox3.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox3.setText("Jal-jeera");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox3.setOpaque(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox3);
        jCheckBox3.setBounds(10, 120, 160, 30);

        jCheckBox4.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox4.setText("Aam Panna");
        jCheckBox4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox4.setOpaque(false);
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox4);
        jCheckBox4.setBounds(10, 300, 160, 30);

        jCheckBox5.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox5.setText("Nimbu Pani");
        jCheckBox5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox5.setOpaque(false);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox5);
        jCheckBox5.setBounds(10, 360, 160, 30);

        jCheckBox7.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox7.setText("Jigarthanda");
        jCheckBox7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox7.setOpaque(false);
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox7);
        jCheckBox7.setBounds(10, 180, 160, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 102));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("0");
        jTextField1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jTextField1);
        jTextField1.setBounds(210, 300, 50, 30);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(255, 255, 102));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("0");
        jTextField2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField2);
        jTextField2.setBounds(210, 420, 50, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(255, 255, 102));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("0");
        jTextField3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jTextField3);
        jTextField3.setBounds(210, 240, 50, 30);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(255, 255, 102));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("0");
        jTextField4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jTextField4);
        jTextField4.setBounds(210, 60, 50, 30);

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(255, 255, 102));
        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("0");
        jTextField5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jTextField5);
        jTextField5.setBounds(210, 120, 50, 30);

        jTextField6.setEditable(false);
        jTextField6.setBackground(new java.awt.Color(255, 255, 102));
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("0");
        jTextField6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jTextField6);
        jTextField6.setBounds(210, 180, 50, 30);

        jTextField7.setEditable(false);
        jTextField7.setBackground(new java.awt.Color(255, 255, 102));
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("0");
        jTextField7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.add(jTextField7);
        jTextField7.setBounds(210, 360, 50, 30);

        jCheckBox22.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox22.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox22.setText("Sattu Pani");
        jCheckBox22.setOpaque(false);
        jCheckBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox22ActionPerformed(evt);
            }
        });
        jPanel5.add(jCheckBox22);
        jCheckBox22.setBounds(10, 420, 150, 41);

        jPanel3.add(jPanel5);
        jPanel5.setBounds(10, 10, 270, 480);

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Agency FB", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("VEGES");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jPanel6.add(jLabel3);
        jLabel3.setBounds(60, 0, 120, 30);

        jCheckBox8.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox8.setText("Palak Bhurji");
        jCheckBox8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox8.setOpaque(false);
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox8);
        jCheckBox8.setBounds(10, 60, 160, 30);

        jCheckBox9.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox9.setText("Palong  Paneer");
        jCheckBox9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox9.setOpaque(false);
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox9);
        jCheckBox9.setBounds(10, 120, 190, 30);

        jCheckBox10.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox10.setText("Motor Panner");
        jCheckBox10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox10.setOpaque(false);
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox10);
        jCheckBox10.setBounds(10, 180, 180, 30);

        jCheckBox11.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox11.setText("Undhiya");
        jCheckBox11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox11.setOpaque(false);
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox11);
        jCheckBox11.setBounds(10, 300, 160, 30);

        jCheckBox12.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox12.setText("Beans Patoli");
        jCheckBox12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox12.setOpaque(false);
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox12);
        jCheckBox12.setBounds(10, 360, 160, 30);

        jCheckBox13.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox13.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox13.setText("Mandi");
        jCheckBox13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox13.setOpaque(false);
        jCheckBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox13ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox13);
        jCheckBox13.setBounds(10, 420, 160, 30);

        jCheckBox14.setFont(new java.awt.Font("Sylfaen", 3, 24)); // NOI18N
        jCheckBox14.setForeground(new java.awt.Color(255, 153, 51));
        jCheckBox14.setText("Methi Aloo");
        jCheckBox14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jCheckBox14.setOpaque(false);
        jCheckBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox14ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox14);
        jCheckBox14.setBounds(10, 240, 160, 30);

        jTextField8.setEditable(false);
        jTextField8.setBackground(new java.awt.Color(255, 255, 102));
        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("0");
        jTextField8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jTextField8);
        jTextField8.setBounds(210, 60, 50, 30);

        jTextField9.setEditable(false);
        jTextField9.setBackground(new java.awt.Color(255, 255, 102));
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("0");
        jTextField9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jTextField9);
        jTextField9.setBounds(210, 120, 50, 30);

        jTextField10.setEditable(false);
        jTextField10.setBackground(new java.awt.Color(255, 255, 102));
        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("0");
        jTextField10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jTextField10);
        jTextField10.setBounds(210, 180, 50, 30);

        jTextField11.setEditable(false);
        jTextField11.setBackground(new java.awt.Color(255, 255, 102));
        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("0");
        jTextField11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jTextField11);
        jTextField11.setBounds(210, 300, 50, 30);

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(255, 255, 102));
        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("0");
        jTextField12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jTextField12);
        jTextField12.setBounds(210, 360, 50, 30);

        jTextField13.setEditable(false);
        jTextField13.setBackground(new java.awt.Color(255, 255, 102));
        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("0");
        jTextField13.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jTextField13);
        jTextField13.setBounds(210, 420, 50, 30);

        jTextField14.setEditable(false);
        jTextField14.setBackground(new java.awt.Color(255, 255, 102));
        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("0");
        jTextField14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.add(jTextField14);
        jTextField14.setBounds(210, 240, 50, 30);

        jPanel3.add(jPanel6);
        jPanel6.setBounds(300, 10, 270, 480);

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Total");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jPanel7.add(jLabel5);
        jLabel5.setBounds(10, 80, 140, 30);

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Sub-Total");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jPanel7.add(jLabel9);
        jLabel9.setBounds(10, 10, 140, 30);

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 0));
        jLabel10.setText("Tax");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jPanel7.add(jLabel10);
        jLabel10.setBounds(10, 45, 140, 30);

        jTextField25.setEditable(false);
        jTextField25.setBackground(new java.awt.Color(255, 255, 102));
        jTextField25.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextField25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField25.setText("Rs 0.0");
        jTextField25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jTextField25);
        jTextField25.setBounds(235, 15, 120, 28);

        jTextField26.setEditable(false);
        jTextField26.setBackground(new java.awt.Color(255, 255, 102));
        jTextField26.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextField26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField26.setText("Rs 0.0");
        jTextField26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jTextField26);
        jTextField26.setBounds(235, 85, 120, 28);

        jTextField27.setEditable(false);
        jTextField27.setBackground(new java.awt.Color(255, 255, 102));
        jTextField27.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextField27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField27.setText("Rs 0.0");
        jTextField27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.add(jTextField27);
        jTextField27.setBounds(235, 50, 120, 28);

        jPanel3.add(jPanel7);
        jPanel7.setBounds(460, 500, 400, 120);

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Cost of Drinks");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jPanel8.add(jLabel6);
        jLabel6.setBounds(20, 10, 250, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Cost of Veges");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jPanel8.add(jLabel7);
        jLabel7.setBounds(20, 45, 250, 30);

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Cost of Non-Veges");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), null, null));
        jPanel8.add(jLabel8);
        jLabel8.setBounds(20, 82, 250, 30);

        jTextField22.setEditable(false);
        jTextField22.setBackground(new java.awt.Color(255, 255, 102));
        jTextField22.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("Rs 0.0");
        jTextField22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jTextField22);
        jTextField22.setBounds(290, 85, 100, 28);

        jTextField23.setEditable(false);
        jTextField23.setBackground(new java.awt.Color(255, 255, 102));
        jTextField23.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setText("Rs 0.0");
        jTextField23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField23);
        jTextField23.setBounds(290, 13, 100, 28);

        jTextField24.setEditable(false);
        jTextField24.setBackground(new java.awt.Color(255, 255, 102));
        jTextField24.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextField24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField24.setText("Rs 0.0");
        jTextField24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jTextField24);
        jTextField24.setBounds(290, 50, 100, 28);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(10, 500, 420, 120);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 62, 870, 635);

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 4));
        jPanel9.setLayout(null);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(255, 204, 102));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 0, 204));
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel9.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 450, 500);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(875, 63, 475, 520);

        jPanel10.setBackground(new java.awt.Color(0, 51, 51));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 0), 4));
        jPanel10.setLayout(null);

        jButton1.setBackground(new java.awt.Color(204, 204, 0));
        jButton1.setFont(new java.awt.Font("Agency FB", 3, 28)); // NOI18N
        jButton1.setText("Reset");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 0), null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1);
        jButton1.setBounds(240, 40, 100, 40);

        jButton2.setBackground(new java.awt.Color(204, 204, 0));
        jButton2.setFont(new java.awt.Font("Agency FB", 3, 28)); // NOI18N
        jButton2.setText("Total");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 0), null, null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton2);
        jButton2.setBounds(10, 40, 110, 40);

        jButton3.setBackground(new java.awt.Color(204, 204, 0));
        jButton3.setFont(new java.awt.Font("Agency FB", 3, 28)); // NOI18N
        jButton3.setText("Reciept");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 0), null, null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton3);
        jButton3.setBounds(130, 40, 100, 40);

        jButton4.setBackground(new java.awt.Color(204, 204, 0));
        jButton4.setFont(new java.awt.Font("Agency FB", 3, 28)); // NOI18N
        jButton4.setText("Exit");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 51, 0), null, null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton4);
        jButton4.setBounds(350, 40, 100, 40);

        jLabel16.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel10.add(jLabel16);
        jLabel16.setBounds(50, 10, 380, 20);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(875, 590, 476, 107);

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
       if(jCheckBox2.isSelected())
       {
           jTextField4.setEditable(true);
           jTextField4.requestFocus();
           jTextField4.setText("");
       }
       else
       {
           jTextField4.setEditable(false);
           jTextField4.setText("0");
       }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox3.isSelected())
       {
           jTextField5.setEditable(true);
           jTextField5.requestFocus();
           jTextField5.setText("");
       }
       else
       {
           jTextField5.setEditable(false);
           jTextField5.setText("0");
       }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
       if(jCheckBox7.isSelected())
       {
           jTextField6.setEditable(true);
           jTextField6.requestFocus();
           jTextField6.setText("");
       }
       else
       {
           jTextField6.setEditable(false);
           jTextField6.setText("0");
       }
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(jCheckBox1.isSelected())
       {
           jTextField3.setEditable(true);
           jTextField3.requestFocus();
           jTextField3.setText("");
       }
       else
       {
           jTextField3.setEditable(false);
           jTextField3.setText("0");
       }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        if(jCheckBox4.isSelected())
       {
           jTextField1.setEditable(true);
           jTextField1.requestFocus();
           jTextField1.setText("");
       }
       else
       {
           jTextField1.setEditable(false);
           jTextField1.setText("0");
       }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        if(jCheckBox5.isSelected())
       {
           jTextField7.setEditable(true);
           jTextField7.requestFocus();
           jTextField7.setText("");
       }
       else
       {
           jTextField7.setEditable(false);
           jTextField7.setText("0");
       }
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
      if(jCheckBox8.isSelected())
       {
           jTextField8.setEditable(true);
           jTextField8.requestFocus();
           jTextField8.setText("");
       }
       else
       {
           jTextField8.setEditable(false);
           jTextField8.setText("0");
       }
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
       if(jCheckBox9.isSelected())
       {
           jTextField9.setEditable(true);
           jTextField9.requestFocus();
           jTextField9.setText("");
       }
       else
       {
           jTextField9.setEditable(false);
           jTextField9.setText("0");
       }
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        if(jCheckBox10.isSelected())
       {
           jTextField10.setEditable(true);
           jTextField10.requestFocus();
           jTextField10.setText("");
       }
       else
       {
           jTextField10.setEditable(false);
           jTextField10.setText("0");
       }
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox14ActionPerformed
        if(jCheckBox14.isSelected())
       {
           jTextField14.setEditable(true);
           jTextField14.requestFocus();
           jTextField14.setText("");
       }
       else
       {
           jTextField14.setEditable(false);
           jTextField14.setText("0");
       }
    }//GEN-LAST:event_jCheckBox14ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
      if(jCheckBox11.isSelected())
       {
           jTextField11.setEditable(true);
           jTextField11.requestFocus();
           jTextField11.setText("");
       }
       else
       {
           jTextField11.setEditable(false);
           jTextField11.setText("0");
       }
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
       if(jCheckBox12.isSelected())
       {
           jTextField12.setEditable(true);
           jTextField12.requestFocus();
           jTextField12.setText("");
       }
       else
       {
           jTextField12.setEditable(false);
           jTextField12.setText("0");
       }
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox13ActionPerformed
        if(jCheckBox13.isSelected())
       {
           jTextField13.setEditable(true);
           jTextField13.requestFocus();
           jTextField13.setText("");
       }
       else
       {
           jTextField13.setEditable(false);
           jTextField13.setText("0");
       }
    }//GEN-LAST:event_jCheckBox13ActionPerformed

    private void jCheckBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox15ActionPerformed
       if(jCheckBox15.isSelected())
       {
           jTextField15.setEditable(true);
           jTextField15.requestFocus();
           jTextField15.setText("");
       }
       else
       {
           jTextField15.setEditable(false);
           jTextField15.setText("0");
       }
    }//GEN-LAST:event_jCheckBox15ActionPerformed

    private void jCheckBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox16ActionPerformed
        if(jCheckBox16.isSelected())
       {
           jTextField16.setEditable(true);
           jTextField16.requestFocus();
           jTextField16.setText("");
       }
       else
       {
           jTextField16.setEditable(false);
           jTextField16.setText("0");
       }
    }//GEN-LAST:event_jCheckBox16ActionPerformed

    private void jCheckBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox17ActionPerformed
       if(jCheckBox17.isSelected())
       {
           jTextField17.setEditable(true);
           jTextField17.requestFocus();
           jTextField17.setText("");
       }
       else
       {
           jTextField17.setEditable(false);
           jTextField17.setText("0");
       }
    }//GEN-LAST:event_jCheckBox17ActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
      if(jCheckBox18.isSelected())
       {
           jTextField21.setEditable(true);
           jTextField21.requestFocus();
           jTextField21.setText("");
       }
       else
       {
           jTextField21.setEditable(false);
           jTextField21.setText("0");
       }
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox21ActionPerformed
        if(jCheckBox21.isSelected())
       {
           jTextField18.setEditable(true);
           jTextField18.requestFocus();
           jTextField18.setText("");
       }
       else
       {
           jTextField18.setEditable(false);
           jTextField18.setText("0");
       }
    }//GEN-LAST:event_jCheckBox21ActionPerformed

    private void jCheckBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox19ActionPerformed
       if(jCheckBox19.isSelected())
       {
           jTextField19.setEditable(true);
           jTextField19.requestFocus();
           jTextField19.setText("");
       }
       else
       {
           jTextField19.setEditable(false);
           jTextField19.setText("0");
       }
    }//GEN-LAST:event_jCheckBox19ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
       if(jCheckBox20.isSelected())
       {
           jTextField20.setEditable(true);
           jTextField20.requestFocus();
           jTextField20.setText("");
       }
       else
       {
           jTextField20.setEditable(false);
           jTextField20.setText("0");
       }
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       jTextField1.setText("0");
       jTextField2.setText("0");
       jTextField3.setText("0");
       jTextField4.setText("0");
       jTextField5.setText("0");
       jTextField6.setText("0");
       jTextField7.setText("0");
       jTextField8.setText("0");
       jTextField9.setText("0");
       jTextField10.setText("0");
       jTextField11.setText("0");
       jTextField12.setText("0");
       jTextField13.setText("0");
       jTextField14.setText("0");
       jTextField15.setText("0");
       jTextField16.setText("0");
       jTextField17.setText("0");
       jTextField18.setText("0");
       jTextField19.setText("0");
       jTextField20.setText("0");
       jTextField21.setText("0");
       jTextField22.setText("Rs 0.0");
       jTextField23.setText("Rs 0.0");
       jTextField24.setText("Rs 0.0");
       jTextField25.setText("Rs 0.0");
       jTextField26.setText("Rs 0.0");
       jTextField27.setText("Rs 0.0");
       jTextArea2.setText("");
       
       jCheckBox1.setSelected(false);
       jCheckBox2.setSelected(false);
       jCheckBox3.setSelected(false);
       jCheckBox4.setSelected(false);
       jCheckBox5.setSelected(false);
       jCheckBox22.setSelected(false);
       jCheckBox7.setSelected(false);
       jCheckBox8.setSelected(false);
       jCheckBox9.setSelected(false);
       jCheckBox10.setSelected(false);
       jCheckBox10.setSelected(false);
       jCheckBox11.setSelected(false);
       jCheckBox12.setSelected(false);
       jCheckBox13.setSelected(false);
       jCheckBox14.setSelected(false);
       jCheckBox15.setSelected(false);
       jCheckBox16.setSelected(false);
       jCheckBox17.setSelected(false);
       jCheckBox18.setSelected(false);
       jCheckBox19.setSelected(false);
       jCheckBox20.setSelected(false);
       jCheckBox21.setSelected(false);
       
       jTextField1.setEditable(false);
       jTextField2.setEditable(false);
       jTextField3.setEditable(false);
       jTextField4.setEditable(false);        
       jTextField5.setEditable(false);
       jTextField6.setEditable(false);
       jTextField7.setEditable(false);
       jTextField8.setEditable(false);      
       jTextField9.setEditable(false);
       jTextField10.setEditable(false);
       jTextField11.setEditable(false);
       jTextField12.setEditable(false);        
       jTextField13.setEditable(false);
       jTextField14.setEditable(false);
       jTextField15.setEditable(false);
       jTextField16.setEditable(false);  
       jTextField17.setEditable(false);
       jTextField18.setEditable(false);
       jTextField19.setEditable(false);
       jTextField20.setEditable(false);        
       jTextField21.setEditable(false);
       
       jLabel16.setText(" ");
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if((jCheckBox1.isSelected()) || (jCheckBox2.isSelected()) ||  (jCheckBox3.isSelected()) || (jCheckBox4.isSelected()) || (jCheckBox5.isSelected()) || (jCheckBox22.isSelected()) || (jCheckBox7.isSelected()) || (jCheckBox8.isSelected()) ||  (jCheckBox9.isSelected()) || (jCheckBox10.isSelected()) ||  (jCheckBox11.isSelected()) || (jCheckBox12.isSelected()) || (jCheckBox13.isSelected()) || (jCheckBox14.isSelected()) || (jCheckBox15.isSelected()) || (jCheckBox16.isSelected()) ||  (jCheckBox17.isSelected()) || (jCheckBox18.isSelected()) || (jCheckBox19.isSelected()) || (jCheckBox20.isSelected()) || (jCheckBox21.isSelected())) 
      {
        f1=Float.parseFloat(jTextField4.getText())*40f;
        f2=Float.parseFloat(jTextField5.getText())*45f;
        f3=Float.parseFloat(jTextField6.getText())*42f;
        f4=Float.parseFloat(jTextField3.getText())*46f;
        f5=Float.parseFloat(jTextField1.getText())*50f;
        f6=Float.parseFloat(jTextField7.getText())*48f;
        f7=Float.parseFloat(jTextField2.getText())*40f;
        total_drinks=(f1+f2+f3+f4+f5+f6+f7);
        
        f8=Float.parseFloat(jTextField8.getText())*50f;
        f9=Float.parseFloat(jTextField9.getText())*57f;
        f10=Float.parseFloat(jTextField10.getText())*55f;
        f11=Float.parseFloat(jTextField14.getText())*52f;
        f12=Float.parseFloat(jTextField11.getText())*54f;
        f13=Float.parseFloat(jTextField12.getText())*58f;
        f14=Float.parseFloat(jTextField13.getText())*56f;
        total_veges=(f8+f9+f10+f11+f12+f13+f14);
        
        f15=Float.parseFloat(jTextField15.getText())*70f;
        f16=Float.parseFloat(jTextField16.getText())*71f;
        f17=Float.parseFloat(jTextField17.getText())*75f;
        f18=Float.parseFloat(jTextField21.getText())*76f;
        f19=Float.parseFloat(jTextField18.getText())*71f;
        f20=Float.parseFloat(jTextField19.getText())*80f;
        f21=Float.parseFloat(jTextField20.getText())*78f;
        total_nonveges=(f15+f16+f17+f18+f19+f20+f21);
        
        
        
        
        
        String s1=Float.toString(total_drinks);
        String s2=Float.toString(total_veges);
        String s3=Float.toString(total_nonveges);
        jTextField23.setText(s1);
        jTextField24.setText(s2);
        jTextField22.setText(s3);
     
         sub_total=total_drinks+total_veges+total_nonveges;
        String s4=Float.toString(sub_total);
        jTextField25.setText(s4);
        
         tax=(sub_total*0.09f);
        String s5=Float.toString(tax);
        jTextField27.setText(s5);
        
        total= sub_total+tax;
        String s6=Float.toString(total);
        jTextField26.setText(s6);
        
        
        jLabel16.setText(" ");
      } else {
          jLabel16.setText("Please choose atleast one item");
          
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           int refs;
           refs=1325+(int)(Math.random()*4238);
           int ref=(refs);
           
           LocalDate d=LocalDate.now();
           LocalTime t=LocalTime.now();
        
        
        if(!((jTextArea2.getText().length())>=1))
       {
          if((jCheckBox1.isSelected()) || (jCheckBox2.isSelected()) ||  (jCheckBox3.isSelected()) || (jCheckBox4.isSelected()) || (jCheckBox5.isSelected()) || (jCheckBox22.isSelected()) || (jCheckBox7.isSelected()) || (jCheckBox8.isSelected()) ||  (jCheckBox9.isSelected()) || (jCheckBox10.isSelected()) ||  (jCheckBox11.isSelected()) || (jCheckBox12.isSelected()) || (jCheckBox13.isSelected()) || (jCheckBox14.isSelected()) || (jCheckBox15.isSelected()) || (jCheckBox16.isSelected()) ||  (jCheckBox17.isSelected()) || (jCheckBox18.isSelected()) || (jCheckBox19.isSelected()) || (jCheckBox20.isSelected()) || (jCheckBox21.isSelected())) 
          {
           jTextArea2.append("                           ::Billing Details::\n");
           jTextArea2.append("                                                      Time:"+t+"\n");
           jTextArea2.append("Reference no: "+ref+"                       Date: "+d+"\n");
           jTextArea2.append("=+=====+=====+======+======+======+====+=\n");
          }
           if((jCheckBox1.isSelected()) || (jCheckBox2.isSelected()) ||  (jCheckBox3.isSelected()) || (jCheckBox4.isSelected()) || (jCheckBox5.isSelected()) || (jCheckBox22.isSelected()) || (jCheckBox7.isSelected()))
           {
           jTextArea2.append("                               Drinks\n");
           jTextArea2.append("                    -------------------------\n");
           }
           
           if(jCheckBox2.isSelected())
               jTextArea2.append(" Sugarcane juice: "+jTextField4.getText()+"                                  "+f1+"\n");
           
           if(jCheckBox3.isSelected())
               jTextArea2.append(" Jal-jeera:             "+jTextField5.getText()+"                                  "+f2+"\n");
          
          if(jCheckBox7.isSelected())
               jTextArea2.append(" Jigarthanda:        "+jTextField6.getText()+"                                  "+f3+"\n");
          
          if(jCheckBox1.isSelected())
               jTextArea2.append(" Shikanji:              "+jTextField3.getText()+"                                  "+f4+"\n");
         
          if(jCheckBox4.isSelected())
               jTextArea2.append(" Aam Panna:        "+jTextField1.getText()+"                                  "+f5+"\n");
         
          if(jCheckBox5.isSelected())
               jTextArea2.append(" Nimbu Pani:        "+jTextField7.getText()+"                                  "+f6+"\n");
          
          if(jCheckBox22.isSelected())
               jTextArea2.append(" Sattu Pani:          "+jTextField2.getText()+"                                  "+f7+"\n");
           if((jCheckBox1.isSelected()) || (jCheckBox2.isSelected()) ||  (jCheckBox3.isSelected()) || (jCheckBox4.isSelected()) || (jCheckBox5.isSelected()) || (jCheckBox22.isSelected()) || (jCheckBox7.isSelected()))
           {
           jTextArea2.append("\n::Total cost of Drinks:-Rs "+total_drinks+"\n\n");
           }
          
          
          
          if((jCheckBox8.isSelected()) || (jCheckBox9.isSelected()) ||  (jCheckBox10.isSelected()) || (jCheckBox11.isSelected()) || (jCheckBox12.isSelected()) || (jCheckBox13.isSelected()) || (jCheckBox14.isSelected()))
          { 
           jTextArea2.append("                              Veges\n");
           jTextArea2.append("                    ---------------------------\n");
          }
           
           if(jCheckBox8.isSelected())
               jTextArea2.append(" Palak Bhurji:       "+jTextField8.getText()+"                                   "+f8+"\n");
           
           if(jCheckBox9.isSelected())
               jTextArea2.append(" Palong  Paneer:  "+jTextField9.getText()+"                                   "+f9+"\n");
          
            if(jCheckBox10.isSelected())
               jTextArea2.append(" Motor Panner:     "+jTextField10.getText()+"                                   "+f10+"\n");
          
            if(jCheckBox14.isSelected())
               jTextArea2.append(" Methi Aloo:          "+jTextField14.getText()+"                                   "+f11+"\n");
         
            if(jCheckBox11.isSelected())
               jTextArea2.append(" Undhiya:              "+jTextField11.getText()+"                                   "+f12+"\n");
         
            if(jCheckBox12.isSelected())
               jTextArea2.append(" Beans Patoli:       "+jTextField12.getText()+"                                   "+f13+"\n");
          
            if(jCheckBox13.isSelected())
               jTextArea2.append(" Mandi:                 "+jTextField13.getText()+"                                    "+f14+"\n");
             
          if((jCheckBox8.isSelected()) || (jCheckBox9.isSelected()) ||  (jCheckBox10.isSelected()) || (jCheckBox11.isSelected()) || (jCheckBox12.isSelected()) || (jCheckBox13.isSelected()) || (jCheckBox14.isSelected()))
          {
           jTextArea2.append("\n::Total cost of Veges:-Rs "+total_veges+"\n\n");         
          }
            
            
            
           
           if((jCheckBox15.isSelected()) || (jCheckBox16.isSelected()) ||  (jCheckBox17.isSelected()) || (jCheckBox18.isSelected()) || (jCheckBox19.isSelected()) || (jCheckBox20.isSelected()) || (jCheckBox21.isSelected()))
           {            
           jTextArea2.append("                             Non-Veges\n");
           jTextArea2.append("                    ----------------------------\n");
           }
           
           if(jCheckBox15.isSelected())
               jTextArea2.append(" Mutton Korma:     "+jTextField15.getText()+"                                   "+f15+"\n");
           
           if(jCheckBox16.isSelected())
               jTextArea2.append(" Chiken Reajala:   "+jTextField16.getText()+"                                   "+f16+"\n");
          
            if(jCheckBox17.isSelected())
               jTextArea2.append(" Katla Fish Kari:    "+jTextField17.getText()+"                                   "+f17+"\n");
          
            if(jCheckBox18.isSelected())
               jTextArea2.append(" Katol Kalia:          "+jTextField21.getText()+"                                   "+f18+"\n");
         
            if(jCheckBox21.isSelected())
               jTextArea2.append(" Chiken 65:           "+jTextField18.getText()+"                                   "+f19+"\n");
         
            if(jCheckBox19.isSelected())
               jTextArea2.append(" Nihari Gosht:       "+jTextField19.getText()+"                                   "+f20+"\n");
          
            if(jCheckBox20.isSelected())
               jTextArea2.append(" Butter chiken:      "+jTextField20.getText()+"                                   "+f21+"\n");
         if((jCheckBox15.isSelected()) || (jCheckBox16.isSelected()) ||  (jCheckBox17.isSelected()) || (jCheckBox18.isSelected()) || (jCheckBox19.isSelected()) || (jCheckBox20.isSelected()) || (jCheckBox21.isSelected()))
           {            
           jTextArea2.append("\n::Total Cost of Non-Veges:-Rs "+total_nonveges+"\n\n");
           
           }
       if((jCheckBox1.isSelected()) || (jCheckBox2.isSelected()) ||  (jCheckBox3.isSelected()) || (jCheckBox4.isSelected()) || (jCheckBox5.isSelected()) || (jCheckBox22.isSelected()) || (jCheckBox7.isSelected()) || (jCheckBox8.isSelected()) ||  (jCheckBox9.isSelected()) || (jCheckBox10.isSelected()) ||  (jCheckBox11.isSelected()) || (jCheckBox12.isSelected()) || (jCheckBox13.isSelected()) || (jCheckBox14.isSelected()) || (jCheckBox15.isSelected()) || (jCheckBox16.isSelected()) ||  (jCheckBox17.isSelected()) || (jCheckBox18.isSelected()) || (jCheckBox19.isSelected()) || (jCheckBox20.isSelected()) || (jCheckBox21.isSelected())) 
        {
        jTextArea2.append("****************************************************************");
        jTextArea2.append("\nSub Total:    "+"Rs."+sub_total);
        jTextArea2.append("\nTax:              "+"Rs."+tax);
        jTextArea2.append("\nTotal:            "+"Rs."+total);
        jTextArea2.append("\n=+=====+======+======+======+====+===+==+=");
        jTextArea2.append("\n                               * Thank  You *");
        
        }
           
           
        }
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jCheckBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox22ActionPerformed
       if(jCheckBox22.isSelected())
        {
           jTextField2.setEditable(true);
           jTextField2.requestFocus();
           jTextField2.setText("");
       }
       else
       {
           jTextField2.setEditable(false);
           jTextField2.setText("0");
       }
    }//GEN-LAST:event_jCheckBox22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
